name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (for optional static tooling)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/doc

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
